### ISSUE TITLE
Visual runner using config error

### ISSUE THREAD

**Issue by darrenkeenn** [sbm007/pixl-js#1]
Hi,

Big fan of your work!

Having an issue with using the config file to run the tests and see them at the same time. Getting the following:
```
Pixl.js: Error - Async worker threw error. { Error: ENOENT: no such file or directory, mkdir '.../vr_data/vr_runs/1560182158232/test_name/mobile'
    at Object.fs.mkdirSync (fs.js:885:18)
    at PixlJs._createFolders (/...node_modules/pixl-js/lib/engine.js:92:10)
    at PixlJs.runScenario (/.../node_modules/pixl-js/lib/engine.js:159:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/.../vr_data/vr_runs/1560182158232/test)bane/mobile' }
```

This is using the following config:

```
{
  "url": "http://localhost:3009/",
  "headless": false,
  "misMatchPercentage": 0,
  "maxRunsToKeep": 5,
  "maxWorkers": 8,
  "viewports": [
    {
      "name": "mobile",
      "width": 320
    },
    {
      "name": "tabletPortrait",
      "width": 768
    },
    {
      "name": "tabletLandscape",
      "width": 1024
    },
    {
      "name": "desktop",
      "width": 1440
    }
  ],
  "outputDirectory": "./module_name/vr_data",
  "beforeEach": "./module_name/features/setup.js",
  "scenarios": "./module_name/features/**/*.pup.js"
}

```

Thanks!

**Comment by sbm007** [comment]
Glad to hear it!

Can you confirm what command you are using to run the unit tests? You should be running:

```
pixl-js run ./config.pixl-js.json
```

In the same folder as where the `config.pixl-js.json` lives

Also please make sure the following directory exists (relative from the config file):

```
./module_name/vr_data/
```

**Comment by darrenkeenn** [comment]
Can confirm I am using all of the above and still receiving the error. I am even getting it on modules that were previously made...

**Comment by sbm007** [comment]
Very strange. Have you tried ruling permissions out as the issue? Check your user owns all the folders you are attempting to write to (using chown) and you have the write bit set on all files and folders (chmod -R).

If it still causes issues, can you try cloning this repo and run pixl-js in isolation just to make sure it’s not a system issue instead of project config.

**Comment by sbm007** [comment]
I believe I know what the issue is. The pixl-js engine relies on the recursive option for fs.mkdir. This is only supported in Node 10+. Therefore if you are using Node 8, you will run into the above error. 

I will get a fix raised in the next few days. 

Hope that helps.

**Comment by darrenkeenn** [comment]
Tried and works. Thanks for the help.
